"""
Django settings for smartcity_app project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0jmw^a4oh5^*7c9i6h1_$arc0ziyly1lwg@=@@ruz$6%mp_(cj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Diubah ke '*' khusus untuk kebutuhan shared-server praktikum agar fleksibel [cite: 51]
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # App Proyek Sebelumnya
    'main_app',
    'about',
    'contacts',
    
    # App Baru Lab Session 6
    'usermanagement_24782061',

    # App Baru Lab Session 7
    'dashboard_24782061', 

    # App Baru Lab Session 9
    'rest_framework', 

    # App Baru Lab Session 10 (JWT Authentication)
    'rest_framework_simplejwt', 

    # App Baru Lab Session 11 (CORS Headers) [cite: 48]
    'corsheaders', 
]

MIDDLEWARE = [
    # CorsMiddleware WAJIB diletakkan paling atas sebelum middleware lainnya [cite: 49]
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# DISESUAIKAN: Mengarah ke folder konfigurasi yang baru [cite: 43]
ROOT_URLCONF = 'smartcity_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates', 
            BASE_DIR / 'usermanagement_24782061',
            BASE_DIR / 'main_app' / 'templates', 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# DISESUAIKAN: Mengarah ke file wsgi yang baru [cite: 44]
WSGI_APPLICATION = 'smartcity_app.wsgi.application'


# Database
# Menggunakan MySQL sesuai konfigurasi XAMPP kamu saat di lokal.
# Catatan: Ketika di server, bagian ini dikonfigurasi ulang ke PostgreSQL sesuai ketentuan modul[cite: 100].
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smartcity_db_new',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# TAMBAHAN WAJIB: Tempat pengumpulan aset statis DRF untuk dibaca Nginx/Gunicorn di server [cite: 54, 103, 104]
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================================
# KONFIGURASI CUSTOM USER MODEL (LAB SESSION 6)
# ==========================================================
AUTH_USER_MODEL = 'usermanagement_24782061.User'

# Pengaturan Redirect Autentikasi
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'  
LOGOUT_REDIRECT_URL = 'login' 

# ==========================================================
# KONFIGURASI DJANGO REST FRAMEWORK & JWT (LAB SESSION 10)
# ==========================================================
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # <--- Tambahan agar bisa Login via Browser
    ),
}

# Pengaturan Masa Aktif Token JWT agar tidak cepat habis saat testing/demo tugas
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==========================================================
# KONFIGURASI CORS SETTINGS (LAB SESSION 11 & LAB SESSION 13)
# ==========================================================
# Diwajibkan bernilai True khusus di production praktikum agar GitHub Pages bisa cross-origin ke Server Kampus [cite: 52, 56]
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]

# Mengizinkan pengiriman kredensial / header otorisasi antar port lokal/publik
CORS_ALLOW_CREDENTIALS = True

# Menambahkan izin eksplisit untuk jenis headers yang dikirim oleh SPA frontend (terutama Authorization Bearer)
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]