# Generated by Django 4.2 on 2026-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Infrastruktur', 'Infrastruktur'), ('Keamanan', 'Keamanan'), ('Kesehatan', 'Kesehatan'), ('Lampu Mati', 'Lampu Mati'), ('Drainase', 'Drainase'), ('Jalan Rusak', 'Jalan Rusak'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=100),
        ),
    ]
