# Generated by Django 4.2 on 2026-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Infrastruktur', 'Infrastruktur'), ('Keamanan', 'Keamanan'), ('Kesehatan', 'Kesehatan'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=100),
        ),
    ]
