# Generated by Django 4.2 on 2026-06-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Infrastruktur', 'Infrastruktur'), ('Keamanan', 'Keamanan'), ('Kebersihan', 'Kebersihan'), ('Kesehatan', 'Kesehatan'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=100),
        ),
    ]
